"""Generated by figtune — panel merge script

Self-contained: each panel's code was copied into this file, so it draws the
figure on its own. The panel scripts are no longer needed, and moving or
renaming them does not affect this file. The flip side is that later edits to
a panel script do not show up here — merge again to pick them up.

The result is an ordinary matplotlib Figure, so figtune can open and edit it
as a whole, and this file runs without figtune.

CELLS gives each panel its place as (row, col, rowspan, colspan), so a panel
may span several grid cells.
"""

import matplotlib.pyplot as plt

# (row, col, rowspan, colspan) — same order as the panel functions below
CELLS = [(0, 0, 1, 1), (0, 1, 1, 1), (1, 0, 1, 1), (1, 1, 1, 1)]

PANEL_LABELS = ['(a)', '(b)', '(c)', '(d)']


def _panel_0(ax):
    """예제 패널: 흡수 곡선.

    `plot(ax)`를 노출하는 형태다. 이 한 가지만 지키면 figtune이 이 파일을
    다른 패널들과 하나의 figure로 합칠 수 있다. `__main__` 블록이 있으므로
    단독 실행도 그대로 된다.

    figtune은 이 파일을 절대 수정하지 않는다.
    """
    import numpy as np
    import matplotlib.pyplot as plt

    RNG = np.random.default_rng(42)
    KE = 0.09                      # 흡수 속도 상수 (1/h)
    PLATEAU = 3.5                  # 정상상태 농도


    def plot(ax):
        t = np.linspace(0, 48, 24)
        pred = PLATEAU * (1 - np.exp(-KE * t))
        obs = pred + RNG.normal(0, 0.12, t.size)

        ax.plot(t, obs, "o", label="Observed", markersize=4)
        ax.plot(t, pred, "-", label="DEB-TK")
        ax.set_xlabel("Time (h)")
        ax.set_ylabel("Concentration (ug/g)")
        ax.set_title("Uptake")
        ax.legend()

    plot(ax)


def _panel_1(ax):
    """예제 패널: 용량-반응 (seaborn hue).

    seaborn이 hue 범례를 만들려고 데이터 점이 0개인 artist를 남기는 경우다.
    figtune 트리에서 그것들은 `(범례 전용)`으로 표시된다 — 색을 바꿔도 화면에
    아무 일이 없는 이유를 알 수 있게.
    """
    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns

    RNG = np.random.default_rng(7)


    def plot(ax):
        groups = np.repeat(["low", "mid", "high"], 30)
        vals = np.concatenate([RNG.normal(m, 0.4, 30) for m in (1.0, 1.8, 2.9)])
        sns.scatterplot(x=RNG.uniform(0, 1, 90), y=vals, hue=groups, ax=ax)
        ax.set_xlabel("Exposure")
        ax.set_ylabel("Response")
        ax.set_title("Dose response")

    plot(ax)


def _panel_2(ax):
    """예제 패널: 막대. patches가 그룹으로 묶여 트리에 나오는 경우다."""
    import numpy as np
    import matplotlib.pyplot as plt

    TREATMENTS = ("control", "low", "mid", "high")
    MEANS = (1.0, 1.4, 2.2, 3.1)
    ERRORS = (0.12, 0.15, 0.21, 0.28)


    def plot(ax):
        x = np.arange(len(TREATMENTS))
        ax.bar(x, MEANS, yerr=ERRORS, capsize=3)
        ax.set_xticks(x)
        ax.set_xticklabels(TREATMENTS)
        ax.set_ylabel("Body burden")
        ax.set_title("By treatment")

    plot(ax)


def _panel_3(ax):
    """예제 패널: 배출 곡선. y축 라벨이 일부러 짧다.

    패널마다 y라벨 길이가 다르면 단순 타일링으로는 그림틀이 어긋난다.
    figtune의 모드 A는 axes 상자를 기준으로 맞추고, 모드 B는 하나의 격자에
    그리므로 둘 다 이 문제를 피한다.
    """
    import numpy as np
    import matplotlib.pyplot as plt

    RNG = np.random.default_rng(11)


    def plot(ax):
        t = np.linspace(0, 72, 30)
        for k, label in ((0.05, "slow"), (0.12, "fast")):
            y = 3.5 * np.exp(-k * t) + RNG.normal(0, 0.05, t.size)
            ax.plot(t, y, "o-", markersize=3, label=label)
        ax.set_xlabel("Time (h)")
        ax.set_ylabel("C")
        ax.set_title("Elimination")
        ax.legend(frameon=False)

    plot(ax)


PANELS = [_panel_0, _panel_1, _panel_2, _panel_3]

fig = plt.figure(figsize=(8.0, 6.0))
_gs = fig.add_gridspec(2, 2)
_axes = [fig.add_subplot(_gs[_r:_r + _rs, _c:_c + _cs])
         for _r, _c, _rs, _cs in CELLS]

for _draw, _ax in zip(PANELS, _axes):
    _draw(_ax)

for _ax, _label in zip(_axes, PANEL_LABELS):
    _ax.text(-0.15, 1.02, _label, transform=_ax.transAxes,
             fontweight="bold", fontsize=11, va="bottom", ha="left")

fig.tight_layout()
