"""Generated by figtune — panel merge script

Self-contained: each panel's code was copied into this file, so it draws the
figure on its own. The panel scripts are no longer needed, and moving or
renaming them does not affect this file. The flip side is that later edits to
a panel script do not show up here — merge again to pick them up.

The result is an ordinary matplotlib Figure, so figtune can open and edit it
as a whole, and this file runs without figtune.

CELLS gives each panel its place as (row, col, rowspan, colspan), so a panel
may span several grid cells.
"""

import matplotlib.pyplot as plt

# (row, col, rowspan, colspan) — same order as the panel functions below
CELLS = [(0, 0, 1, 1), (0, 1, 1, 1), (1, 0, 1, 2)]

# Each panel's projection, or None for an ordinary 2D axes. An axes' class is
# fixed when it is created (Axes3D, PolarAxes, …), so a 3D panel needs the
# right kind of axes from the start — it cannot be converted afterwards.
PROJECTIONS = [None, None, None]

# A panel that already draws several axes keeps its own grid: its region is
# subdivided into (rows, cols) and it receives that list of axes. (1, 1) means
# an ordinary single-axes panel.
INNER = [(1, 1), (1, 1), (1, 2)]

PANEL_LABELS = ['(a)', '(b)', '(c)', '(d)']


def _panel_0(ax):
    """예제 패널: 흡수 곡선.

    `plot(ax)`를 노출하는 형태다. 이 한 가지만 지키면 figtune이 이 파일을
    다른 패널들과 하나의 figure로 합칠 수 있다. `__main__` 블록이 있으므로
    단독 실행도 그대로 된다.

    figtune은 이 파일을 절대 수정하지 않는다.
    """
    import numpy as np
    import matplotlib.pyplot as plt

    RNG = np.random.default_rng(42)
    KE = 0.09                      # 흡수 속도 상수 (1/h)
    PLATEAU = 3.5                  # 정상상태 농도


    def plot(ax):
        t = np.linspace(0, 48, 24)
        pred = PLATEAU * (1 - np.exp(-KE * t))
        obs = pred + RNG.normal(0, 0.12, t.size)

        ax.plot(t, obs, "o", label="Observed", markersize=4)
        ax.plot(t, pred, "-", label="DEB-TK")
        ax.set_xlabel("Time (h)")
        ax.set_ylabel("Concentration (ug/g)")
        ax.set_title("Uptake")
        ax.legend()

    plot(ax)


def _panel_1(ax):
    """예제 패널: 용량-반응 (seaborn hue).

    seaborn이 hue 범례를 만들려고 데이터 점이 0개인 artist를 남기는 경우다.
    figtune 트리에서 그것들은 `(범례 전용)`으로 표시된다 — 색을 바꿔도 화면에
    아무 일이 없는 이유를 알 수 있게.
    """
    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns

    RNG = np.random.default_rng(7)


    def plot(ax):
        groups = np.repeat(["low", "mid", "high"], 30)
        vals = np.concatenate([RNG.normal(m, 0.4, 30) for m in (1.0, 1.8, 2.9)])
        sns.scatterplot(x=RNG.uniform(0, 1, 90), y=vals, hue=groups, ax=ax)
        ax.set_xlabel("Exposure")
        ax.set_ylabel("Response")
        ax.set_title("Dose response")

    plot(ax)


def _panel_2(axs):
    def _draw(axs):
        fig = axs[0].figure
        axes = axs
        """예제: 멀티패널 figure. figtune은 이 파일을 절대 수정하지 않는다."""
        import numpy as np
        import matplotlib.pyplot as plt
        import seaborn as sns

        rng = np.random.default_rng(42)
        t = np.linspace(0, 48, 24)
        obs = 3.5 * (1 - np.exp(-0.09 * t)) + rng.normal(0, 0.12, t.size)
        pred = 3.5 * (1 - np.exp(-0.09 * t))


        axes[0].plot(t, obs, "o", label="Observed", markersize=4)
        axes[0].plot(t, pred, "-", label="DEB-TK")
        axes[0].set_xlabel("Time (h)")
        axes[0].set_ylabel("Concentration")
        axes[0].set_title("Uptake")
        axes[0].legend()

        groups = np.repeat(["low", "mid", "high"], 30)
        vals = np.concatenate([rng.normal(m, 0.4, 30) for m in (1.0, 1.8, 2.9)])
        sns.scatterplot(x=rng.uniform(0, 1, 90), y=vals, hue=groups, ax=axes[1])
        axes[1].set_xlabel("Exposure")
        axes[1].set_ylabel("Response")
        axes[1].set_title("Dose response")

        fig.tight_layout()

    _draw(axs)


PANELS = [_panel_0, _panel_1, _panel_2]

fig = plt.figure(figsize=(8.0, 6.0))
_gs = fig.add_gridspec(2, 2)

_axes = []          # every axes, in reading order — the labels follow this
_targets = []       # what each panel is handed: one axes, or a list of them
for (_r, _c, _rs, _cs), _p, (_ir, _ic) in zip(CELLS, PROJECTIONS, INNER):
    _spec = _gs[_r:_r + _rs, _c:_c + _cs]
    _kw = {} if _p is None else {"projection": _p}
    if (_ir, _ic) == (1, 1):
        _a = fig.add_subplot(_spec, **_kw)
        _axes.append(_a)
        _targets.append(_a)
    else:
        _sub = _spec.subgridspec(_ir, _ic)
        _group = [fig.add_subplot(_sub[_i, _j], **_kw)
                  for _i in range(_ir) for _j in range(_ic)]
        _axes.extend(_group)
        _targets.append(_group)

for _draw, _t in zip(PANELS, _targets):
    _draw(_t)

for _ax, _label in zip(_axes, PANEL_LABELS):
    # Axes3D.text takes (x, y, z, s); text2D is the 2D-in-axes-coords one.
    _put = getattr(_ax, "text2D", None) or _ax.text
    _put(-0.15, 1.02, _label, transform=_ax.transAxes,
         fontweight="bold", fontsize=11, va="bottom", ha="left")

fig.tight_layout()
